function Hd = filter_code
%FILTER_CODE Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 25.2 and Signal Processing Toolbox 25.2.
% Generated on: 30-Nov-2025 10:51:53

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 5000;  % Sampling Frequency

N    = 200;      % Order
Fc   = 60;       % Cutoff Frequency
flag = 'scale';  % Sampling Flag
Beta = 2;        % Window Parameter

% Create the window vector for the design algorithm.
win = kaiser(N+1, Beta);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
